"""
api.py
======
Deployment layer for AssetFlow's Asset Risk Prediction module.

This file ONLY exposes the already-trained, already-validated model as a
REST API. It does not retrain, does not touch preprocessing/feature
engineering, and does not change any thresholds - it simply imports and
calls the existing `predict_asset_risk()` function from predict.py exactly
as-is.

Consumed by: the AssetFlow backend team, to power:
    - Screen 4 (Asset Directory) - Risk column, one call per asset
    - Screen 2 (Dashboard KPI)   - "Assets at Risk" count, backend aggregates
      risk_label == "High" across calls (no separate model / endpoint needed)

Run:
    uvicorn api:app --reload

Docs:
    http://localhost:8000/docs   (Swagger UI, auto-generated by FastAPI)
    http://localhost:8000/redoc  (ReDoc, alternative view)
"""

import logging
from typing import Optional

from fastapi import FastAPI, HTTPException, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, ConfigDict

# ------------------------------------------------------------------
# Reuse the existing, already-trained prediction function AS-IS.
# Importing this module also loads asset_risk_model.pkl and encoder.pkl
# once (at import time) via predict.py's own module-level loading code -
# we do not duplicate or re-implement that loading logic here.
# ------------------------------------------------------------------
from predict import predict_asset_risk

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("assetflow-risk-api")


# ============================================================================
# Pydantic request/response models
# ============================================================================
class AssetInput(BaseModel):
    """
    Raw asset fields required by the risk model, mirroring the columns the
    model was trained on (see preprocess.py). This is the exact request
    body backend developers must send to POST /predict.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "asset_type": "Vehicle",
                "department": "Operations",
                "purchase_date": "2021-01-07",
                "asset_age_years": 5.51,
                "purchase_cost": 21500.00,
                "condition": "Poor",
                "status": "Allocated",
                "allocation_count": 6,
                "booking_count_last_12_months": 1,
                "utilization_ratio": 0.657,
                "maintenance_count": 4,
                "maintenance_cost": 900.0,
                "days_since_last_maintenance": 33,
                "days_since_last_allocation": 13,
                "idle_days": 59,
                "warranty_expired": True,
            }
        }
    )

    asset_type: str = Field(..., description="e.g. Laptop, Vehicle, Printer, Server, Furniture")
    department: str = Field(..., description="e.g. IT, HR, Finance, Sales, Operations, Marketing")
    purchase_date: str = Field(..., description="ISO date string, e.g. '2021-01-07'")
    asset_age_years: float = Field(..., ge=0, description="Age of the asset in years")
    purchase_cost: float = Field(..., ge=0, description="Original purchase cost")
    condition: str = Field(..., description="Excellent, Good, Fair, or Poor")
    status: str = Field(..., description="Available, Allocated, Under Maintenance, Reserved, or Retired")
    allocation_count: int = Field(..., ge=0, description="Total number of times the asset has been allocated")
    booking_count_last_12_months: int = Field(..., ge=0, description="Bookings in the last 12 months")
    utilization_ratio: float = Field(..., ge=0, le=1, description="Fraction of time the asset is in active use (0-1)")
    maintenance_count: int = Field(..., ge=0, description="Total number of maintenance events")
    maintenance_cost: float = Field(..., ge=0, description="Cumulative maintenance cost")
    days_since_last_maintenance: int = Field(..., ge=0, description="Days since the asset was last serviced")
    days_since_last_allocation: int = Field(..., ge=0, description="Days since the asset was last allocated")
    idle_days: int = Field(..., ge=0, description="Days the asset has sat idle")
    warranty_expired: bool = Field(..., description="Whether the warranty has expired")


class RiskPredictionResponse(BaseModel):
    """Exact response shape returned by predict_asset_risk() - passed through unchanged."""

    risk_score: float = Field(..., description="Predicted risk score, 0.0-1.0")
    risk_label: str = Field(..., description="Low, Medium, or High - derived from risk_score")
    reason: str = Field(..., description="Rule-based, human-readable explanation (not model output)")


class RootResponse(BaseModel):
    status: str
    service: str
    version: str


class ErrorResponse(BaseModel):
    detail: str


# ============================================================================
# FastAPI app
# ============================================================================
app = FastAPI(
    title="AssetFlow Asset Risk Prediction API",
    description=(
        "Inference API wrapping AssetFlow's trained Asset Risk Prediction model. "
        "Powers the Risk column on the Asset Directory (Screen 4) and the "
        "'Assets at Risk' KPI on the Dashboard (Screen 2). "
        "This service only serves predictions - it does not train or modify the model."
    ),
    version="1.0",
)

# NOTE on model/encoder loading:
# predict.py loads asset_risk_model.pkl and encoder.pkl once at MODULE
# IMPORT time (see its `_model_bundle = joblib.load(...)` lines at module
# scope). Because Python caches imports, the `from predict import
# predict_asset_risk` statement above already triggers that load exactly
# once when this API process starts - every request afterward reuses the
# same in-memory model. We deliberately do not re-load anything in a
# startup event handler, to avoid loading it twice.
logger.info("AssetFlow Risk Prediction API starting up - model artifacts loaded via predict.py import.")


# ============================================================================
# Routes
# ============================================================================
@app.get(
    "/",
    response_model=RootResponse,
    summary="Health check",
    tags=["Health"],
)
def read_root() -> RootResponse:
    """Simple liveness/health check endpoint."""
    return RootResponse(
        status="running",
        service="AssetFlow Asset Risk Prediction API",
        version="1.0",
    )


@app.post(
    "/predict",
    response_model=RiskPredictionResponse,
    responses={
        422: {"model": ErrorResponse, "description": "Validation error - malformed or missing fields"},
        500: {"model": ErrorResponse, "description": "Internal prediction error"},
    },
    summary="Predict risk for a single asset",
    tags=["Prediction"],
)
def predict(asset: AssetInput) -> RiskPredictionResponse:
    """
    Score a single asset's risk.

    Pydantic (via `AssetInput`) validates types and required fields before
    this function body ever runs - malformed requests are automatically
    rejected with HTTP 422 and a field-level error message, so no manual
    type-checking is needed here.

    The actual prediction logic (preprocessing, model inference, and the
    rule-based `reason` text) lives entirely in predict.predict_asset_risk()
    and is untouched by this layer.
    """
    try:
        # Pydantic v2: model_dump() converts the validated request into the
        # plain dict shape predict_asset_risk() expects.
        asset_dict = asset.model_dump()
        result = predict_asset_risk(asset_dict)
        return RiskPredictionResponse(**result)

    except Exception as exc:
        # Any failure inside the existing, already-validated ML pipeline is
        # unexpected at this point (inputs are already type/range-checked
        # by Pydantic) - log it for debugging and surface a clean 500
        # rather than leaking a raw stack trace to the caller.
        logger.exception("Prediction failed for input: %s", asset.model_dump())
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Prediction failed: {exc}",
        ) from exc


# ============================================================================
# Global handler: turn FastAPI/Pydantic validation errors into a clean,
# consistent error shape (still uses FastAPI's default 422 status code).
# ============================================================================
from fastapi.exceptions import RequestValidationError
from fastapi.requests import Request


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
    """
    FastAPI already returns HTTP 422 for validation errors by default; this
    handler just normalizes the payload shape to {"detail": "..."} so
    backend consumers can rely on one consistent error format across every
    endpoint of this API.
    """
    first_error = exc.errors()[0]
    field = ".".join(str(loc) for loc in first_error["loc"] if loc != "body")
    message = f"{field}: {first_error['msg']}" if field else first_error["msg"]
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"detail": message},
    )
